mypor/mypor/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mypor/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
     path('', views.IndexView.as_view(), name='main'),
     #path('', views.main, name='main'),
     path('new', views.post_new, name='post_new'),
     
]

mypor/post/models.py
from django.utils  import timezone
from datetime import date 
from django.db import models
from multiselectfield import MultiSelectField
#from array_field_select.fields import ArrayField

# Create your models here.

def default_city(): # user가 회원가입할 때 지정한? 도시 or seoul
    return "seoul"

class Post(models.Model):
    Location_list =(
        ('서울특별시','서울특별시'),
        ('부산광역시','부산광역시'),
        ('세종특별시','세종특별시'),
        ('충청북도','충청북도'),
        ('충청남도','충청남도'),
        ('전라북도','전라북도'),
        ('전라남도','전라남도'),
        ('대구광역시','대구광역시'),
        ('제주특별시','제주특별시'),
        ('경상북도','경상북도'),
        ('경상남도','경상남도'),     
    )

    Category_list = (  
        ('study','StudyRoom'), 
        ('performance','PerformanceRoom'),
        ('practice','PracticeRoom'),
        ('etc','etc'),
    )
    
    Option_list =(
        ('vim','vim'),
        ('board', 'board'),
        ('desk', 'desk'),
        ('multitap','multitap'),
        ('speaker','speaker'),
        ('lights','lights'),
        ('mirror','mirror'),
        ('air','airconditioner'),
        ('printer','printer'),
    )

        
    title = models.CharField(max_length=50)
    context = models.TextField()
    choose_date = models.DurationField() #!!!!!!! 일정 기간을 저장하는 필드를 만들기    
    '''지역 선택'''
    #location = ArrayField( models.CharField(choices=Location_list, max_length=30, default=default_city))
    location = models.CharField(choices=Location_list, max_length=30, default=default_city)
    '''공간 유형 선택'''
    category = MultiSelectField(choices=Category_list, max_length=50, blank=True)
    etc_what = models.CharField(max_length=50, null=True,blank=True)
    '''물건 대여 선택'''
    Option = MultiSelectField(choices=Option_list, max_length=50,default=False, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)  # 글 작성 시간 :  시간이 있는 날짜를 저장하는 datetime 필드를 만들기 
    Modified_date = models.DateTimeField(auto_now=True) # 글 게시 날짜 

    def __str__(self):
        return "RoomShare : {}".format(self.title)
    
    def ROOM_TYPE(self):
        if self.category=='etc' :
            return "ROOM etc :{}".format(self.etc_what) 

mypor/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','category','etc_what','Option','choose_date','context')
    
    

mypor/post/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView
from .models import Post
from .forms import PostForm
from django.http import HttpResponse

# def main(request):
#     post_list = Post.objects.all().order_by('Modified_date')[:10]
#     context = {'post_list': post_list }
#     return render(request, 'post/post_list.html', context)

class IndexView(ListView):
    model = 'Post'
    template_name = 'post/post_list.html' # 디폴트 템플릿명: <app_label>/<model_name>_list.html
    context_object_name = 'post_list' # 디폴트 컨텍스트 변수명 :  object_list
    
    def get_queryset(self): # 컨텍스트 오버라이딩
      return Post.objects.order_by('Modified_date')[:5]

class DetailView(DetailView):
    model = 'Post'# 해당 모델 - URLConf 의 PK 변수를 활용하여 해당 모델의 특정 record를 컨텍스트 변수(object)에 담는다.
    template_name = 'post/post_detail.html' # 디폴트 템플릿명: <app_label>/<model_name>_detail.html
    context_object_name = 'posts' # 디폴트 컨텍스트 변수명 :  object


#create
def post_new(request):
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit = False)
            # post.Modified_date = request.META['Modified_date']
            post.save()
            return redirect('post:IndexView')
    else:
        form = PostForm()
    return render(request, 'post/post_new.html',{'form':form,})



def word_filter(field_names):
    # data_file = open("C:/Users/user/Desktop/욕목록.txt","r") 
    # words = data_file.read().split(",")
    # sentence = ""
    # for field_name in field_names:
    #     for term in words: 
    #         if term in field_name: 
    #             field_name =  field_name.replace(term, "초롱이") 
    #     sentence = sentence + " " + field_name
    # return(sentence)    
    pass

mypor/templates/post/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>post_detail</title>
</head>
<body>
    
</body>
</html>

mypor/templates/post/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Room_Share_main</title>
</head>
<body>

    <h1>main 페이지</h1>
    {% for post in post_list %}
       <div>
            <p><a href="{% url 'post:post_new' %}">방 올리기</a></p>
            <p>{{post.title}}</p>
            <p>{{post.choose_date}}</p>
            <p>수정일: {{ post.Modified_date }}</p>
       </div>
    {%endfor%}


</body>
</html>

mypor/templates/post/post_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>post_new</title>
</head>
<body>
        <form action="" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit">
        </form>    
</body>
</html>